#!/bin/bash
#I expect the following variables to be exported in run_ctest
{
  echo "INTEGERVAR1: \"$INTEGERVAR1\""
  echo "INTEGERVAR2: \"$INTEGERVAR2\""
  echo "FLOATVAR: \"$FLOATVAR\""
  echo "STRINGVAR: \"$STRINGVAR\""
  echo "VARWITHSPACES: \"$VARWITHSPACES\""
} > exportedVariables

