#!/bin/bash
#I expect the following variables to be exported in run_ctest

{
  if [[ "$args" = "a beautiful collection of arguments with quotes" ]]; then 
    echo "arguments are passed correcly"
    else
    echo "arguments are NOT passed correcly"
  fi
} > arguments

