site_name: PLUMED manual

nav:
  - Introduction: 'index.md'
  - Modules: 'modules.md'
  - Actions: 'actionlist.md'
  - Getting started: 'https://www.plumed-tutorials.org/lessons/21/001/data/NAVIGATION.html'
  - Tutorials: 'https://www.plumed-tutorials.org'
  - Publications: 'https://www.plumed-nest.org'

not_in_nav: |
  *.md
  !index.md

extra_css:
   - assets/plumedtohtml.css
   - https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-flash-1.5.6/b-html5-1.5.6/datatables.min.css
   - https://cdn.datatables.net/v/dt/jq-3.3.1/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-flash-1.5.6/b-html5-1.5.6/datatables.min.css

extra_javascript:
  - assets/plumedtohtml.js
  - https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
  - assets/tablecode.js
  - assets/mathjax.js
  - https://cdn.datatables.net/v/dt/jq-3.3.1/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-flash-1.5.6/b-html5-1.5.6/datatables.min.js

markdown_extensions:
  - mdx_math
