name: CI

on:
  push:
  pull_request:

env:
# on CI, better dump stack trace in case there is an error
  PLUMED_STACK_TRACE: yes
# use two threads for openMP tests
  PLUMED_NUM_THREADS: 2
# these are used to build required packages
  CC: gcc
  CXX: g++

jobs:
  macsimple:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Set paths
      run: |
        echo "$HOME/opt/bin" >> $GITHUB_PATH
        echo "CPATH=$HOME/opt/include:$CPATH" >> $GITHUB_ENV
        echo "INCLUDE=$HOME/opt/include:$INCLUDE" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$HOME/opt/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/opt/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Build PLUMED
      run: |
        # it seems brew update is screwing up something
        # GB on Mar 8, 2024
        #brew update > /dev/null
        brew install gawk
        ./configure --disable-dependency-tracking --prefix="$HOME/opt"
        make -j 4
        make install
    - name: Run tests
      run: make -C regtest/basic/rt-make-moduleMap 
         